export const PERSON_LIST_REQUEST = 'PERSON_LIST_REQUEST'
export const PERSON_LIST_SUCCESS = 'PERSON_LIST_SUCCESS'
export const PERSON_LIST_FAIL = 'PERSON_LIST_FAIL'

export const PERSON_DETAILS_REQUEST = 'PERSON_DETAILS_REQUEST'
export const PERSON_DETAILS_SUCCESS = 'PERSON_DETAILS_SUCCESS'
export const PERSON_DETAILS_FAIL = 'PERSON_DETAILS_FAIL'
